# The layers for which an analysis should be performed.
layers:
  - Consensus
  - Execution

mode:
  - Countries
  - Organizations

execution_parameters:
  concurrency: 100

output_directories:  
  - ./output
