# The layers for which an analysis should be performed.
layers:
  - Consensus
  - Execution

mode:
  - Countries
  - Organizations

execution_parameters:
  concurrency: 100

output_directories:  
  - ./output

# Metrics for network analysis (organizations)
network_metrics:
  - HHI
  - Nakamoto
#  - Entropy
  - Concentration Ratio

# Metrics for geographic analysis (countries)
geo_metrics:
  - HHI
  - Nakamoto
  - Entropy
  - Concentration Ratio

# Parameters for metric computation
metrics_parameters:
  concentration_ratio_topn:
    - 1
    - 3