# The ledgers for which an analysis should be performed.
ledgers:
  - bitcoin
  - bitcoin_cash
  - dogecoin
  - litecoin
  - zcash

execution_parameters:
  concurrency: 100

# The number of packets to consider when cleaning up
last_time_active: 1

# Paths to directories of snapshot db files; either absolute or relative from run.py.
# The first path will be used to write newly created dbs and the output of runs
output_directories:  
  - ./output
